{% set name = "spacy-langdetect" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc04e22e35f12d7fb4a86cda888da8d2529ca9569437cbd6925544babf1ee62e

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pytest
    - langdetect 1.0.7

test:
  imports:
    - spacy_langdetect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Abhijit-2592/spacy-langdetect
  summary: Fully customizable language detection pipeline for spaCy
  description: Fully customizable language detection pipeline for spaCy
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/Abhijit-2592/spacy-langdetect
  dev_url: https://github.com/Abhijit-2592/spacy-langdetect

extra:
  recipe-maintainers:
    - boldorider4
